"use client";

import { useRouter } from 'next/navigation';
import RevenueChart from '@/components/charts/RevenueChart';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

export default function RevenuePage() {
    const router = useRouter();

    return (
        <div className="min-h-screen bg-[#0B0E12] text-white p-4 max-w-[400px] mx-auto">
            <div className="flex items-center gap-4 mb-8">
                <Button
                    variant="ghost"
                    size="icon"
                    onClick={() => router.back()}
                    className="text-zinc-400 hover:text-white"
                >
                    <ArrowLeft className="w-5 h-5" />
                </Button>
                <h1 className="text-xl font-bold">Revenue History</h1>
            </div>

            <div className="space-y-6">
                <div className="p-4 rounded-xl bg-[#13161F] border border-white/5">
                    <h2 className="text-xs text-zinc-400 font-medium uppercase tracking-wide mb-4">
                        Cartel 7-Day Performance
                    </h2>
                    <RevenueChart range="7d" />
                </div>

                <div className="p-4 rounded-xl bg-[#13161F]/50 border border-white/5">
                    <p className="text-xs text-zinc-500 leading-relaxed">
                        This chart shows the daily revenue generated by the Cartel through Raids and High Stakes events. Use this data to track the empire's growth.
                    </p>
                </div>
            </div>
        </div>
    );
}
